/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCFAUTO001FUNC
#define ROOCFAUTO001FUNC

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCFAuto001Func : public RooAbsReal {
public:
  RooCFAuto001Func() {} ; 
  RooCFAuto001Func(const char *name, const char *title,
	      RooAbsReal& _efficiency_kappa,
	      RooAbsReal& _beta_efficiency);
  RooCFAuto001Func(const RooCFAuto001Func& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCFAuto001Func(*this,newname); }
  inline virtual ~RooCFAuto001Func() { }

protected:

  RooRealProxy efficiency_kappa ;
  RooRealProxy beta_efficiency ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCFAuto001Func,1) // Your description goes here...
};
 
#endif
