/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCFAUTO000FUNC
#define ROOCFAUTO000FUNC

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCFAuto000Func : public RooAbsReal {
public:
  RooCFAuto000Func() {} ; 
  RooCFAuto000Func(const char *name, const char *title,
	      RooAbsReal& _lumi_kappa,
	      RooAbsReal& _beta_lumi);
  RooCFAuto000Func(const RooCFAuto000Func& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCFAuto000Func(*this,newname); }
  inline virtual ~RooCFAuto000Func() { }

protected:

  RooRealProxy lumi_kappa ;
  RooRealProxy beta_lumi ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCFAuto000Func,1) // Your description goes here...
};
 
#endif
